apiVersion: v1
kind: Pod
metadata:
  name: formatter-pod
  namespace: shz
  labels:
    name: formatter-pod
    app: shz-apps
spec:
  containers:
  - name: shz-formatter
    image: shz-formatter
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9099