apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: formatter-replicaset
  namespace: shz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shz-apps
  template:
    metadata:
      labels:
        app: shz-apps
    spec:
      containers:
      - name: shz-formatter
        image: shz-formatter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9099
