apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter-deployment
  namespace: shz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shz-apps
  template:
    metadata:
      labels:
        app: shz-apps
    spec:
      containers:
      - name: shz-formatter
        image: shz-formatter:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_HEALTH_ADDL_INFO
          valueFrom:
            configMapKeyRef:
              name: formatter-config
              key: APP_HEALTH_ADDL_INFO
        ports:
        - containerPort: 9099
        resources:
          limits:
            cpu: "1"  # 1 CPU core
            memory: "512Mi"  # 512 MiB
          requests:
            cpu: "500m"  # 0.5 CPU cores
            memory: "256Mi"  # 256 MiB
