
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  application:
    name: Shz Formatter Service

  profiles:
    active: dev

server:
  port: ${SERVER_PORT:9099}
  servlet:
    contextPath: /shz-formatter-svc/
  max-http-header-size: 20000

