
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  application:
    name: Shz Formatter Service

  profiles:
    active: dev

server:
  port: ${SERVER_PORT:9099}
  servlet:
    contextPath: /shz-formatter-svc/
  max-http-header-size: 20000
  
app:
  currency:
    exchange-rate-client:
      url: https://api.apilayer.com/exchangerates_data/latest?base={base}&symbols={symbols}
      apikey: cJLA8bMJsV7kDaF0kjvZ68Lw5HM4vqJ8
      supported-symbols: USD,EUR,GBP,INR
      default-base-symbol: EUR

